spring:
  application:
      name: ToiYeuIT
  #profiles:
   # //active: @spring.profiles.active@
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: "jdbc:mysql://localhost:3306/${DB_DATABASE}?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

env:
  frontend_port: ${FRONTEND_PORT}

jwt:
  valid-duration: 1 #hours
  refresh-duration: 72 # hours
credential:
  admin-email: ${ADMIN_EMAIL}
  admin-password: ${ADMIN_PASSWORD}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem