spring:
  application:
      name: ToiYeuIT
  #profiles:
   # //active: @spring.profiles.active@
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: "jdbc:mysql://localhost:3306/${DB_DATABASE}?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "local.env.properties"
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
    show-sql: true
    open-in-view: true
    properties:
      hibernate:

  mail:
    host: smtp.gmail.com
    port: 587
    username: haycuoinhieuhon1412@gmail.com
    password: oead fvby qxfh vjiz
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
     #     connectiontimeout: 5000
          timeout: 3000
      #    writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
              google:
                client-id: 621389070737-fg51k2vn7mhnu3v9frfbhbbuk2iv242v.apps.googleusercontent.com
                client-secret: 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
                scope:
                  - email
                  - profile

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

env:
  frontend_port: ${FRONTEND_PORT}

jwt:
  valid-duration: 168 #hours
  refresh-duration: 72 # hours
credential:
  admin-email: ${ADMIN_EMAIL}
  admin-password: ${ADMIN_PASSWORD}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  file:
    name: springboot-logs.log
    path: ./logs/
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

payment:
  vnPay:
    tmnCode: R1K6B5W8
    secretKey: P2ERZMFRSYGFWKX9HRRZ6PD1TGUKV2DK
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    version: 2.1.0
    command: pay
    orderType: other
#    change this to frontend port later
    returnUrl: http://localhost:3001/vnpay
