spring:
  application:
      name: ToiYeuIT

  datasource:
    username: root
    password: 17071134
    url: jdbc:mysql://localhost:3306/ToiYeuIT?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

