spring:
  application:
      name: ToiYeuIT
  #profiles:
   # //active: @spring.profiles.active@
  config:
    import: classpath:/env.properties
  datasource:
    username: root
    password: ${LOCAL_DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/${DB_DATABASE}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

