spring:
  application:
      name: ToiYeuIT

  config:
    import: classpath:/env.properties
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

