name: Cai nay giup auto test va deploy ne 

on:
  pull_request:
    branches:
      - main  
  push:
    branches:
      - main
      - mikudeptrai
jobs:
  build-deploy:
     runs-on: self-hosted
     env:
         APP_PATH: ./backend/ToiYeuIT/
         IMAGE_NAME: ToiYeuIT
         PORT: 8081:8081
         TAG: v1.0
         CONTAINER_NAME: ToiYeuITApp
     steps:
        - name: checkout
          uses: actions/checkout@v4

  
        - name: Login to Docker Hub
            # Sử dụng action "docker/login-action" để đăng nhập vào Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Maven
          uses: stCarolas/setup-maven@v5
          with:
            maven-version: 3.8.2

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin' 
            cache: maven
        
        - name: Set up maven
          run:  cd ${{ env.APP_PATH }} && mvn clean install -Pprod

        - name: Build Docker image 
          run: docker build -t ${{ env.IMAGE_NAME  }} ${{   env.APP_PATH   }}

        - name: Build Docker image
          run:  docker push ${{secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
  

  run-service:
    needs: build-deploy
    runs-on: self-hosted

    steps:
      - name: Pull image from dockerhub
        run: docker pull  ${{  secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Stop and remove latest container 
        run: |
            docker stop ${{env.CONTAINER_NAME}}
            docker run  -d --name -p ${{env.PORT}} ${{env.CONTAINER_NAME}} ${{secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
